(feat) Adding Chaos Engineering
natenho/Mockaco pull request #136
Opened 2024-07-16 21:10 UTC by lanegoolsby

This is a direct copy of https://github.com/natenho/Mockaco/pull/114/files, I just addressed the PR feedback. I have a need for this feature and that other PR stalled. :)

2024-08-22 01:24 UTC, lanegoolsby commented
Hey @natenho, mind taking a look at this PR please?

2024-08-22 01:57 UTC, natenho commented on src/Mockaco.AspNetCore/Chaos/Strategies/ChaosStrategyException.cs
> +        var bodyBytes = Encoding.UTF8.GetBytes($"Error {httpResponse.StatusCode}: {HttpStatusCode.ServiceUnavailable}");
The status code in the string is ServiceUnavailable, I suppose you mean InternalServerError, right?

2024-08-22 02:03 UTC, natenho commented on src/Mockaco.AspNetCore/DependencyInjection/MockacoServiceCollection.cs
> +                .AddSingleton<IChaosStrategy, ChaosStrategyBehavior>()
Do we really need singletons here? I would make any dependency as transient by default if I dont need a singleton..it is much easier to deal with concurrent requests in transient objects if we need some context inside the behavior

2024-08-22 04:09 UTC, natenho requested changes
@lanegoolsby there you go! The code is very good, we can merge it asap if you could please review the pr comments! :)

2024-08-25 23:23 UTC, natenho commented
@lanegoolsby  I took the liberty of making the changes to avoid taking even more time to do the merge. Thank you for your contribution!

2024-08-25 23:23 UTC, natenho approved these changes

2024-08-25 23:28 UTC, merged

2024-08-26 14:26 UTC, lanegoolsby commented
Thank you!!